name: BlackBE
main: xyz.blackbe.blackbeplugin.BlackBEMain
version: "1.3.1"
api: ["1.0.0"]
load: POSTWORLD
author: "darker"
description: BlackBE NK Plugin blacbe.xyz

permissions:
  blackbe.command.default:
    description: BlackBE 云黑插件权限
    default: op